#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2021 csharper2005
#
###
### Checks internet connection and restarts
### WWAN interface if internet has lost
###

# Common vars
CHECK_IP="8.8.8.8"
WWAN_IFACE="LTE"
WWAN_DEV="wwan0"
PING_MAX_RETRIES=3
IFACE_MAX_RESTARTS=3
MODEM_RESTART_CMD="AT+QPOWD=1"
MODEM_TTY="/dev/ttyUSB2"

# Wait a bit
sleep 60

# Lets decrease the latency (for MBIM only)
echo "0" > /sys/class/net/$WWAN_DEV/cdc_ncm/tx_timer_usecs

fails_counter=0
iface_restart_counter=0

# Main loop
while [ true ]; do
	if [ $iface_restart_counter -eq $IFACE_MAX_RESTARTS ]; then
		logger "[${0##*/}] Interface $WWAN_IFACE was restarted $IFACE_MAX_RESTARTS times without success"
		echo $MODEM_RESTART_CMD | atinout - $MODEM_TTY - >/dev/null 2>&1
		logger "[${0##*/}] Modem on $MODEM_TTY has been restarted"
		iface_restart_counter=0
		sleep 30
		continue
	fi
	if [ $fails_counter -eq $PING_MAX_RETRIES ]; then
		kernel_err=$(dmesg | grep "Not tainted")
		if [ ! -z "$kernel_err" ]; then
			reboot
		fi
		logger "[${0##*/}] Ping $CHECK_IP failed $PING_MAX_RETRIES times"
		ubus -S call network.interface.$WWAN_IFACE down >/dev/null 2>&1
		sleep 5
		killall uqmi >/dev/null 2>&1
		ubus -S call network.interface.$WWAN_IFACE up >/dev/null 2>&1
		logger "[${0##*/}] Interface $WWAN_IFACE has been restarted"
		iface_restart_counter=$((iface_restart_counter+1))
		sleep 5
	fi
	sleep 5
	fails_counter=0
	while [ $fails_counter -lt $PING_MAX_RETRIES ]; do
		if /bin/ping -I $WWAN_DEV -c 1 $CHECK_IP >/dev/null 2>&1
		then
			break
		fi
		fails_counter=$((fails_counter+1))
	done
done
